import argparse
import csv
import shutil
from collections import Counter
from pathlib import Path


DEFAULT_CLASSES = ["glass", "metal", "other", "paper", "plastic"]


def parse_args():
    parser = argparse.ArgumentParser(
        description="Prepare pseudo-labeled crop folders for manual review and correction"
    )
    parser.add_argument(
        "--manifest",
        default="datasets/parks_cls_unsorted/crops_manifest.csv",
        help="Crop manifest generated by export/auto-label pipeline",
    )
    parser.add_argument(
        "--out-root",
        default="datasets/parks_cls_review",
        help="Output root for review folders and review manifest",
    )
    parser.add_argument(
        "--pool-root",
        default="datasets/parks_cls_pool",
        help="Target root where approved manual labels should be placed",
    )
    parser.add_argument(
        "--min-cls-conf",
        type=float,
        default=0.80,
        help="Classification confidence threshold below which a crop is flagged for review",
    )
    parser.add_argument(
        "--min-det-conf",
        type=float,
        default=0.15,
        help="Detection confidence threshold below which a crop is flagged for review",
    )
    parser.add_argument(
        "--classes",
        nargs="+",
        default=DEFAULT_CLASSES,
        help="Expected material classes",
    )
    parser.add_argument(
        "--clear",
        action="store_true",
        help="Clear review folders before repopulating them",
    )
    return parser.parse_args()


def load_rows(manifest_path: Path):
    if not manifest_path.exists():
        raise FileNotFoundError(f"Manifest not found: {manifest_path}")
    with manifest_path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def safe_float(value, default=0.0):
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def ensure_dirs(root: Path, classes):
    for bucket in ("all_by_pred", "accept_candidate", "review_needed"):
        for class_name in classes:
            (root / bucket / class_name).mkdir(parents=True, exist_ok=True)


def clear_dirs(root: Path):
    if root.exists():
        shutil.rmtree(root)


def main():
    args = parse_args()

    manifest_path = Path(args.manifest)
    out_root = Path(args.out_root)
    pool_root = Path(args.pool_root)

    rows = load_rows(manifest_path)
    if args.clear:
        clear_dirs(out_root)

    ensure_dirs(out_root, args.classes)
    for class_name in args.classes:
        (pool_root / class_name).mkdir(parents=True, exist_ok=True)

    bucket_counts = Counter()
    class_counts = Counter()
    review_rows = []

    for row in rows:
        crop_path = Path(row["crop_path"])
        if not crop_path.exists():
            continue

        class_name = row.get("cls_name", "unknown")
        if class_name not in args.classes:
            class_name = "other" if "other" in args.classes else args.classes[0]

        cls_score = safe_float(row.get("cls_score"))
        det_score = safe_float(row.get("det_score"))
        needs_review = cls_score < args.min_cls_conf or det_score < args.min_det_conf
        bucket = "review_needed" if needs_review else "accept_candidate"

        all_dest = out_root / "all_by_pred" / class_name / crop_path.name
        bucket_dest = out_root / bucket / class_name / crop_path.name
        all_dest.parent.mkdir(parents=True, exist_ok=True)
        bucket_dest.parent.mkdir(parents=True, exist_ok=True)

        shutil.copy2(crop_path, all_dest)
        shutil.copy2(crop_path, bucket_dest)

        bucket_counts[bucket] += 1
        class_counts[class_name] += 1
        review_rows.append(
            {
                "crop_path": crop_path.as_posix(),
                "predicted_class": class_name,
                "cls_score": cls_score,
                "det_score": det_score,
                "review_bucket": bucket,
                "source_image": row.get("source_image", ""),
                "manual_target_hint": (pool_root / class_name / crop_path.name).as_posix(),
            }
        )

    review_manifest = out_root / "review_manifest.csv"
    with review_manifest.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=[
                "crop_path",
                "predicted_class",
                "cls_score",
                "det_score",
                "review_bucket",
                "source_image",
                "manual_target_hint",
            ],
        )
        writer.writeheader()
        writer.writerows(review_rows)

    print(f"[INFO] Review manifest: {review_manifest}")
    print(f"[INFO] Total crops prepared: {sum(class_counts.values())}")
    print(f"[INFO] accept_candidate: {bucket_counts['accept_candidate']}")
    print(f"[INFO] review_needed: {bucket_counts['review_needed']}")
    print("[INFO] By predicted class:")
    for class_name in args.classes:
        print(f" - {class_name}: {class_counts[class_name]}")
    print("[INFO] Manual workflow:")
    print(f" - Review crops in: {out_root / 'all_by_pred'}")
    print(f" - Focus first on: {out_root / 'review_needed'}")
    print(f" - Move approved crops into: {pool_root / '<class>'}")


if __name__ == "__main__":
    main()